// // let a = 10;
// // let b = ++a;
// // console.log(b); //11
// // let a = 10;
// // let b = a++;
// // console.log(b); //10
// let a = 11;
// let b = 22;
// let c = a++ + ++b;
// console.log(c);
// let v = 20;
// console.log(v);
// console.log(v++ + ++v);
// console.log(v);
// console.log(v++ + v);

// console.log(v);
// console.log(++v);
// let t = 71;
// f = t++ + ++t;
// console.log(f);

// let r = 1;
// let n = 2;

// console.log(r++ + ++n); //4
// let g = true; //1
// g++;
// console.log(g);
//MATH FUNCTION
1; //math.floor()

// let a = Math.floor(32 / 3);
let a = Math.ceil(32 / 3);

console.log(32 / 3);
console.log(a);
let b = Math.round(230.1);
console.log(b);
