// // let a = 10;
// // let b = ++a;
// // console.log(b); //11
// // let a = 10;
// // let b = a++;
// // console.log(b); //10
// let a = 11;
// let b = 22;
// let c = a++ + ++b;
// console.log(c);
// let v = 20;
// console.log(v);
// console.log(v++ + ++v);
// console.log(v);
// console.log(v++ + v);

// console.log(v);
// console.log(++v);
// let t = 71;
// f = t++ + ++t;
// console.log(f);

// let r = 1;
// let n = 2;

// console.log(r++ + ++n); //4
// let g = true; //1
// g++;
// console.log(g);
//MATH FUNCTION
1; //math.floor()

// let a = Math.floor(32 / 3);
// let a = Math.ceil(32 / 3);

// console.log(32 / 3);
// console.log(a);
// let b = Math.round(230.1);
// console.log(b);
//sweap//
// let a = 10;
// let b = 20;
//first way do this 20,10 //

// let c = a;
// a = b;
// b = c;

// console.log(a, b);

//2nd way to do this//
// let c;
// c = a;
// a = b;
// b = c;

//third way to swips//
// [a, b] = [b, a];
// console.log(a, b);
// a = a + b; //30
// b = -b;
// b = c - a;
// console.log(a, b);
// let a = 10;
// let b = 120;
// let c = ++a;
// let d = b++ + b;
// console.log(a);
// console.log(d);
let a = 20;
let b = 6;
// let c = Math.floor(a / b);
let c = 20 % 6;

console.log(c);
// console.log(Math.floor(Math.random() * 1000 + 1000));
